backend:
  name: github
  repo: Leonce973/leonce-site
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Accueil"
        name: "accueil"
        file: "index.html"
        fields:
          - { Créer admin/config.yml }
